// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 import 'firebase_options.dart';
// ...
await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9puwKycZ4N-LasVQ2F4rdPUcHAwq3Sew',
    appId: '1:901410395579:web:7ef1ca7dfebd3776aba09e',
    messagingSenderId: '901410395579',
    projectId: 'webradioapp-4d03b',
    authDomain: 'webradioapp-4d03b.firebaseapp.com',
    storageBucket: 'webradioapp-4d03b.appspot.com',
    measurementId: 'G-TCBG4RKMM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA878O9zAEw7ieGT4oGg7RuOTVRrTvHXP8',
    appId: '1:901410395579:android:d55bf0f0bb07ae6daba09e',
    messagingSenderId: '901410395579',
    projectId: 'webradioapp-4d03b',
    storageBucket: 'webradioapp-4d03b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF2AMB7axP9XWNZ7aNZxWL_e-Gy-Sr4TQ',
    appId: '1:901410395579:ios:ab6102247ee4983baba09e',
    messagingSenderId: '901410395579',
    projectId: 'webradioapp-4d03b',
    storageBucket: 'webradioapp-4d03b.appspot.com',
    iosBundleId: 'com.example.webRadioApp',
  );
}
